Add HTMLParserBuilder, VaporDSL
carson-katri/awesome-result-builders pull request #22
Opened 2022-07-14 15:22 UTC by danny1113

2022-07-19 18:52 UTC, carson-katri requested changes

2022-07-19 18:52 UTC, carson-katri commented on README.md
> +	* [HTML Parser](#html-parser)
Could you put it in the HTML section instead of making a new section? I wouldn't be opposed to a new `Parsing` section if you think that fits it better? `HTML Parser` just seems too specific.

2022-07-20 04:55 UTC, danny1113 commented on README.md
> +	* [HTML Parser](#html-parser)
Ok, I think `Parsing` is great!

2022-07-20 19:42 UTC, carson-katri commented
Great, thanks!

2022-07-20 19:42 UTC, merged